export const egyptCities: { name: string; value: string }[] = [
  { name: "Cairo | القاهرة", value: "Cairo" },
  { name: "Alexandria | الإسكندرية", value: "Alexandria" },
  { name: "Giza | الجيزة", value: "Giza" },
  { name: "Port Said | بورسعيد", value: "Port Said" },
  { name: "Suez | السويس", value: "Suez" },
  { name: "Luxor | الأقصر", value: "Luxor" },
  { name: "Asyut | أسيوط", value: "Asyut" },
  { name: "Ismailia | الإسماعيلية", value: "Ismailia" },
  { name: "Faiyum | الفيوم", value: "Faiyum" },
  { name: "Minya | المنيا", value: "Minya" },
  { name: "Zagazig | الزقازيق", value: "Zagazig" },
  { name: "Damietta | دمياط", value: "Damietta" },
  { name: "Aswan | أسوان", value: "Aswan" },
  { name: "Mansoura | المنصورة", value: "Mansoura" },
  { name: "Tanta | طنطا", value: "Tanta" },
  { name: "Zefta | زفتى", value: "Zefta" },
  { name: "Beni Suef | بني سويف", value: "Beni Suef" },
  { name: "Hurghada | الغردقة", value: "Hurghada" },
  { name: "Qena | قنا", value: "Qena" },
  { name: "Sohag | سوهاج", value: "Sohag" },
  { name: "Minya | المنيا", value: "Minya" },
  { name: "Kafr El-Sheikh | كفر الشيخ", value: "Kafr ash shaykh" },
  { name: "Al Khankah | الخنقه", value: "Al Khankah" },
  { name: "6th of October | السادس من أكتوبر", value: "6th of October" },
  { name: "Banha | بنها", value: "Banha" },
  { name: "Arish | العريش", value: "Arish" },
  { name: "Sharm El-Sheikh | شرم الشيخ", value: "Sharm el sheikh" },
  { name: "Marsa Matruh | مرسى مطروح", value: "Marsa Matruh" },
  { name: "Damanhur | دمنهور", value: "Damanhur" },
  {
    name: "El-Mahalla El-Kubra | المحلة الكبرى",
    value: "Al Mahallah al Kubra",
  },
  { name: "Beni Mazar | بني مزار", value: "Beni Mazar" },
  { name: "Helwan | حلوان", value: "Helwan" },
];
